server:
  context-path: /spring-cloud-config-server
  port: 7082

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/agannamaneni/SpringBootApplication
          search-paths: spring-cloud-config-client